# https://docs.google.com/spreadsheets/d/18gBPArJ2abdR3P9BeQw3OD_PLAjITFaE3r82bWUdC8U
ACTORS = [
    "Diddy",
    "Diddy (Instrument)",
    "Diddy (Low Poly)",
    "DK",
    "DK (Low Poly)",
    "Lanky",
    "Lanky (Instrument)",
    "Lanky (Low Poly)",
    "Tiny",
    "Tiny (Instrument)",
    "Tiny (Low Poly)",
    "Chunky",
    "Chunky (Instrument)",
    "Disco Chunky",
    "Chunky (Low Poly)",
    "Invisible Chunky",
    "Cranky",
    "Funky",
    "Candy",
    "Rambi",
    "Snake",
    "Turtle",
    "Seal",
    "Enguarde",
    "Beaver (Low Poly)",
    "Beaver",
    "Beaver (Gold)",
    "Zinger",
    "Squawks",
    "Klobber",
    "Snide",
    "Kaboom",
    "Klaptrap (Green)",
    "Klaptrap (Purple)",
    "Klaptrap (Red)",
    "Klaptrap (Teeth)",
    "Mad Jack",
    "Krash",
    "Troff",
    "Bad Hit Detection Man",
    "Sir Domino",
    "Mr. Dice",
    "Ruler",
    "Robo-Kremling",
    "Scoff",
    "Beetle",
    "Klaptrap (Teeth?)",
    "Nintendo Logo",
    "Kremling",
    "Kremling (Red - Kosh)",
    "Kremling (Green - Kosh)",
    "Mechanical Fish",
    "Toy Car",
    "Giant Clam",
    "Kasplat",
    "Army Dillo",
    "Mr. Dice",
    "Klump",
    "Puftoss",
    "Dogadon",
    "Banana Fairy",
    "Llama",
    "Guard",
    "Robo-Zinger",
    "Turntable",
    "Krossbones",
    "Shuri",
    "Gimpfish",
    "K. Lumsy",
    "Spider",
    "Rabbit",
    "Beanstalk",
    "K. Rool (Cutscene)",
    "Fireball (With Glasses)",
    "Skeleton Head",
    "Skeleton Hand",
    "Vulture (Race)",
    "Vulture (Shooting)",
    "Bat",
    "Skull",
    "Tomato",
    "Kritter-in-a-Sheet",
    "Fly",
    "Fly Swatter",
    "Fly Swatter",
    "Owl",
    "Book",
    "Ship's Wheel",
    "Spotlight Fish",
    "Puftup",
    "Mermaid",
    "Mushroom",
    "Shockwave (Mad Jack)",
    "Squawks",
    "Worm (apple)",
    "Cuckoo Bird",
    "Kosha",
    "Ice Tomato",
    "Army Dillo (No Shell)",
    "Boombox",
    "B. Locker",
    "Escape Ship",
    "Army Dillo's Cannon",
    "K. Rool (Fight)",
    "Golden Banana",
    "Shockwave",
    "K. Rool's Glove",
    "K. Rool's Foot",
    "K. Rool's Toe",
    "K. Rool's Toe",
    "K. Rool's Toe",
    "Microphone",
    "Desk (K. Rool)",
    "Bell",
    "Clapper Board",
    "Cannon",
    "CannonBarrelHUD",
    "Bonus Barrel",
    "Hunky Chunky Barrel",
    "Mini Monkey Barrel",
    "Barrel",
    "Pushable Box",
    "TNT Barrel Spawner",
    "Cannon",
    "TNT Barrel",
    "Rambi Crate",
    "Enguarde Crate",
    "Chain",
    "Swinging Light",
    "Minecart",
    "Barrel",
    "Bridge (Castle)",
    "Large Brown Bridge",
    "Feather",
    "Laser",
    "Golden Banana (Item Drop)",
    "Rocketbarrel",
    "Strong Kong Barrel",
    "Orangstand Sprint Barrel",
    "Diddy's Jetpack",
    "Photo",
    "Minecart (TNT)",
    "Weird glitch texture (computer screen?)",
    "BBB Slot",
    "BBB Slot",
    "BBB Slot",
    "BBB Slot",
    "BBB Lever",
    "Tiny's Car",
    "Missile",
    "Swinging light",
    "Bananaporter Zipper",
    "Boulder",
    "Vase (O)",
    "Vase (:)",
    "Vase (Triangle)",
    "Vase (+)",
    "Toy Box",
    "Boat",
    "Padlock",
    "Cannon Ball",
    "Vine",
    "Vine",
    "Counter",
    "Key",
    "Bongos",
    "DK Star",
    "Spotlight",
    "Cannon (Seasick Chunky)",
    "Boulder Debris",
    "Spider Web",
    "Steel Keg",
    "Shockwave",
    "Shockwave",
    "Battle Crown",
    "Buoy",
    "Buoy (Green)",
    "Nothing?",
    "DK Banana Counter",
    "Diddy Banana Counter",
    "Tiny Banana Counter",
    "Lanky Banana Counter",
    "Chunky Banana Counter",
    "Shockwave (Green)",
    "Potion",
    "Missile (Army Dillo)",
    "Shockwave (Red)",
    "Ice wall?",
    "Rareware Logo",
    "Stalactite",
    "Rock Debris",
    "Spotlight (BONUS)",
    "Tag Barrel",
    "Krossbones Head",
    "Lever",
    "K. Lumsy's Cage",
    "Trap Bubble",
    "1 Pad (Diddy 5DI)",
    "2 Pad (Diddy 5DI)",
    "3 Pad (Diddy 5DI)",
    "4 Pad (Diddy 5DI)",
    "5 Pad (Diddy 5DI)",
    "6 Pad (Diddy 5DI)",
    "Race Checkpoint",
    "Padlock & Key",
    "Finish Line",
    "Shockwave (Green)",
    "Shockwave (Blue)",
    "Shockwave (Purple)",
    "Question Mark",
    "Flower (Instrument)",
    "DK Logo (Instrument)",
    "Golden Banana",
    "Apple",
    "Barrel",
    "Flag",
    "Flag",
    "Boat",
    "Krusha (Gun)",
    "King Kut Out Body",
    "King Kut Out Head",
    "King Kut Out Arm",
    "King Kut Out Arm",
    "Rainbow Coin Patch",
    "Rope",
    "DK Smoke Trail",
    "Light (K. Rool fight)",
    "Bonus Barrel (Hideout Helm)",
    "Banana",
    "Banana Barrel",
    "Training Barrel",
    "Pirate Photo",
    "Butterfly",
    "Barrel",
    "Funky's Gun",
    "Boot"
]
