# https://docs.google.com/spreadsheets/d/18gBPArJ2abdR3P9BeQw3OD_PLAjITFaE3r82bWUdC8U/edit?gid=156575793
PROPS = [
    "Nothing",
    "Thin Flame?",
    "",
    "Tree",
    "",
    "Yellow Flowers",
    "",
    "",
    "Xmas Holly?",
    "",
    "CB Single (Diddy)",
    "Large Wooden Panel",
    "Flames",
    "CB Single (DK)",
    "Large Iron Bars Panel",
    "Goo Hand",
    "Flame",
    "Homing Ammo Crate",
    "Coffin Door",
    "Coffin Lid",
    "Skull",
    "Wooden Crate",
    "CB Single (Tiny)",
    "Shield",
    "Metal thing",
    "Coffin",
    "Metal Panel",
    "Rock Panel",
    "Banana Coin (Tiny)",
    "Banana Coin (DK)",
    "CB Single (Lanky)",
    "CB Single (Chunky)",
    "Tree",
    "",
    "Metal Panel",
    "Banana Coin (Lanky)",
    "Banana Coin (Diddy)",
    "Metal Panel",
    "Metal Panel Red",
    "Banana Coin (Chunky)",
    "Metal Panel Grey",
    "Tree",
    "",
    "CB Bunch (DK)",
    "Hammock",
    "Small jungle bush plant",
    "",
    "Small plant",
    "Bush",
    "",
    "",
    "",
    "Metal Bridge",
    "Large Blue Crystal",
    "Plant",
    "Plant",
    "",
    "White Flowers",
    "Stem 4 Leaves",
    "",
    "",
    "Small plant",
    "",
    "",
    "",
    "",
    "",
    "Yellow Flower",
    "Blade of Grass Large",
    "Lilypad?",
    "Plant",
    "Iron Bars",
    "Nintendo Coin",
    "Metal Floor",
    "",
    "",
    "Bull Rush",
    "",
    "",
    "Metal box/platform",
    "K Crate",
    "",
    "Wooden panel",
    "",
    "",
    "",
    "Orange",
    "Watermelon Slice",
    "Tree",
    "Tree",
    "Tree",
    "Tree (Black)",
    "",
    "Light Green platform",
    "",
    "",
    "",
    "",
    "Brick Wall",
    "",
    "",
    "",
    "",
    "Wrinkly Door (Tiny)",
    "",
    "",
    "",
    "Conveyor Belt",
    "Tree",
    "Tree",
    "Tree",
    "",
    "Primate Punch Switch",
    "Hi-Lo toggle machine",
    "Breakable Metal Grate",
    "Cranky's Lab",
    "Golden Banana",
    "Metal Platform",
    "Metal Bars",
    "",
    "Metal fence",
    "Snide's HQ",
    "Funky's Armory",
    "",
    "Blue lazer field",
    "",
    "Bamboo Gate",
    "",
    "Tree Stump",
    "Breakable Hut",
    "Mountain Bridge",
    "Tree Stump",
    "Bamboo Gate",
    "",
    "Blue/green tree",
    "",
    "Mushroom",
    "",
    "Disco Ball",
    "2 Door (5DS)",
    "3 Door (5DS)",
    "Map of DK island",
    "Crystal Coconut",
    "Ammo Crate",
    "Banana Medal",
    "Peanut",
    "Simian Slam Switch (Chunky, Green)",
    "Simian Slam Switch (Diddy, Green)",
    "Simian Slam Switch (DK, Green)",
    "Simian Slam Switch (Lanky, Green)",
    "Simian Slam Switch (Tiny, Green)",
    "Baboon Blast Pad",
    "Film",
    "Chunky Rotating Room",
    "Stone Monkey Face",
    "Stone Monkey Face",
    "Aztec Panel blue",
    "",
    "Ice Floor",
    "Ice Pole",
    "Big Blue wall panel",
    "Big Blue wall panel",
    "Big Blue wall panel",
    "Big Blue wall panel",
    "KONG Letter (K)",
    "KONG Letter (O)",
    "KONG Letter (N)",
    "KONG Letter (G)",
    "Bongo Pad",
    "Guitar Pad",
    "Saxaphone Pad",
    "Triangle Pad",
    "Trombone Pad",
    "Wood panel small",
    "Wood panel small",
    "Wood panel small",
    "Wood Panel small",
    "Wall Panel",
    "Wall Panel",
    "Stone Monkey Face (Not Solid)",
    "Feed Me Totem",
    "Melon Crate",
    "Lava Platform",
    "Rainbow Coin",
    "Green Switch",
    "Coconut Indicator",
    "Snake Head",
    "Matching Game Board",
    "Stone Monkey Head",
    "Large metal section",
    "Production Room Crusher",
    "Metal Platform",
    "Metal Object",
    "Metal Object",
    "Metal Object",
    "Gong",
    "Platform",
    "Bamboo together",
    "Metal Bars",
    "Target",
    "Wooden object",
    "Ladder",
    "Ladder",
    "Wooden pole",
    "Blue panel",
    "Ladder",
    "Grey Switch",
    "D Block for toy world",
    "Hatch (Factory)",
    "Metal Bars",
    "Raisable Metal Platform",
    "Metal Cage",
    "Simian Spring Pad",
    "Power Shed",
    "Metal platform",
    "Sun Lighting effect panel",
    "Wooden Pole",
    "Wooden Pole",
    "Wooden Pole",
    "",
    "Question Mark Box",
    "Blueprint (Tiny)",
    "Blueprint (DK)",
    "Blueprint (Chunky)",
    "Blueprint (Diddy)",
    "Blueprint (Lanky)",
    "Tree Dark",
    "Rope",
    "",
    "",
    "Lever",
    "Green Croc Head (Minecart)",
    "Metal Gate with red/white stripes",
    "",
    "Purple Croc Head (Minecart)",
    "Wood panel",
    "DK coin",
    "Wooden leg",
    "",
    "Wrinkly Door (Lanky)",
    "Wrinkly Door (DK)",
    "Wrinkly Door (Chunky)",
    "Wrinkly Door (Diddy)",
    "Torch",
    "Number Game (1)",
    "Number Game (2)",
    "Number Game (3)",
    "Number Game (4)",
    "Number Game (5)",
    "Number Game (6)",
    "Number Game (7)",
    "Number Game (8)",
    "Number Game (9)",
    "Number Game (10)",
    "Number Game (11)",
    "Number Game (12)",
    "Number Game (13)",
    "Number Game (14)",
    "Number Game (15)",
    "Number Game (16)",
    "Bad Hit Detection Wheel",
    "Breakable Gate",
    "",
    "Picture of DK island",
    "White flashing thing",
    "Barrel",
    "Gorilla Gone Pad",
    "Monkeyport Pad",
    "Baboon Balloon Pad",
    "Light",
    "Light",
    "Barrel",
    "Barrel",
    "Barrel",
    "Barrel",
    "Pad",
    "Red Light",
    "Breakable X Panel",
    "Power Shed Screen",
    "Crusher",
    "Floor Panel",
    "Metal floor panel mesh",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Toyz Box",
    "O Pad",
    "Bonus Barrel Trap",
    "Sun Idol",
    "Candy's Shop",
    "Pineapple Switch",
    "Peanut Switch",
    "Feather Switch",
    "Grape Switch",
    "Coconut Switch",
    "",
    "Kong Pad",
    "Boss Door",
    "Troff 'n' Scoff Feed Pad",
    "Metal Bars horizontal",
    "Metal Bars",
    "Harbour Gate",
    "K. Rool's Ship",
    "Metal Platform",
    "",
    "Flame",
    "Flame",
    "Scoff n Troff platform",
    "Troff 'n' Scoff Banana Count Pad (DK)",
    "Torch",
    "",
    "",
    "",
    "Boss Key",
    "Machine",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Metal Door",
    "Piano Game",
    "Troff 'n' Scoff Banana Count Pad (Diddy)",
    "Troff 'n' Scoff Banana Count Pad (Lanky)",
    "Troff 'n' Scoff Banana Count Pad (Chunky)",
    "Troff 'n' Scoff Banana Count Pad (Tiny)",
    "Door 1342",
    "Door 3142",
    "Door 4231",
    "1 Switch (Red)",
    "2 Switch (Blue)",
    "3 Switch (Orange)",
    "4 Switch (Green)",
    "",
    "Metal Archway",
    "Green Crystal thing",
    "Red Crystal thing",
    "Propeller",
    "Large Metal Bar",
    "Ray Sheild?",
    "",
    "",
    "",
    "",
    "Light",
    "Target",
    "Ladder",
    "Metal Bars",
    "Red Feather",
    "Grape",
    "Pinapple",
    "Coconut",
    "Rope",
    "On Button",
    "Up Button",
    "Metal barrel or lid",
    "Simian Slam Switch (Chunky, Red)",
    "Simian Slam Switch (Diddy, Red)",
    "Simian Slam Switch (DK, Red)",
    "Simian Slam Switch (Lanky, Red)",
    "Simian Slam Switch (Tiny, Red)",
    "Simian Slam Switch (Chunky, Blue)",
    "Simian Slam Switch (Diddy, Blue)",
    "Simian Slam Switch (DK, Blue)",
    "Simian Slam Switch (Lanky, Blue)",
    "Simian Slam Switch (Tiny, Blue)",
    "Metal Grate",
    "Pendulum",
    "Weight",
    "Door",
    "Day Switch",
    "Night Switch",
    "Hands",
    "Bell",
    "Grate",
    "Crystal",
    "Crystal",
    "Crystal",
    "Door",
    "Gate",
    "Breakable Door",
    "Night Gate",
    "Night Grate",
    "Unknown",
    "Metal Grate",
    "Mill Pulley Mechanism",
    "Metal Bar",
    "Water Wheel",
    "Crusher",
    "Coveyor Belt",
    "Night Gate",
    "Question Mark Box",
    "Spider Web",
    "Grey Croc Head",
    "Caution Sign (Falling Rocks)",
    "Door",
    "Battle Crown",
    "",
    "",
    "Dogadon Arena Background",
    "Skull Door (Small)",
    "Skull Door (Big)",
    "",
    "Tombstone",
    "",
    "DK Star",
    "K. Rool's Throne",
    "Bean",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Power Beam",
    "Warning Lights",
    "K. Rool Door",
    "Metal Grate",
    "Crown Door",
    "Coin Door",
    "Medal Barrier (DK)",
    "Medal Barrier (Diddy)",
    "Medal Barrier (Tiny)",
    "Medal Barrier (Chunky)",
    "Medal Barrier (Lanky)",
    "I Door (Helm, DK)",
    "V Door (Helm, Diddy)",
    "III Door (Helm, Tiny)",
    "II Door (Helm, Chunky)",
    "IV Door (Helm, Lanky)",
    "Metal Door",
    "Stone Wall",
    "Pearl",
    "Small Door",
    "",
    "Cloud",
    "Warning Lights",
    "Door",
    "Mushroom (Yellow)",
    "Mushroom (Purple)",
    "Mushroom (Blue)",
    "Mushroom (Green)",
    "Mushroom (Red)",
    "Mushroom Puzzle Instructions",
    "Face Puzzle Board",
    "Mushroom",
    "Small Torch",
    "DK Arcade Machine",
    "Simian Slam Switch (Any Kong?)",
    "Spotlight (Crown Arena?)",
    "Battle Crown Pad",
    "Seaweed",
    "Light",
    "Dust?",
    "Moon Trapdoor",
    "Ladder",
    "Mushroom Board",
    "DK Star",
    "Wooden Box",
    "Yellow CB Powerup",
    "Blue CB Powerup",
    "Coin Powerup?",
    "DK Coin",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Snide's Mechanism",
    "Blue Flowers",
    "Plant (Green)",
    "Plant (Brown)",
    "Plant",
    "Pink Flowers",
    "Pink Flowers",
    "Plant",
    "Yellow Flowers",
    "Yellow Flowers",
    "Plant",
    "Blue Flowers",
    "Blue Flower",
    "Plant",
    "Plant",
    "Red Flowers",
    "Red Flower",
    "Mushrooms (Small)",
    "Mushrooms (Small)",
    "Purple Flowers",
    "Tree",
    "Cactus",
    "Cactus",
    "Ramp",
    "Submerged Pot",
    "Submerged Pot",
    "Ladder",
    "Ladder",
    "Floor Texture?",
    "Iron Gate",
    "Day Gate",
    "Night Gate",
    "Cabin Door",
    "Ice Wall (Breakable)",
    "Igloo Door",
    "Castle Top",
    "Ice Dome",
    "Boulder Pad",
    "Target",
    "Metal Gate",
    "CB Bunch (Lanky)",
    "CB Bunch (Chunky)",
    "CB Bunch (Tiny)",
    "CB Bunch (Diddy)",
    "Blue Aura",
    "Ice Maze",
    "Rotating Room",
    "Light + Barrier",
    "Light",
    "Trapdoor",
    "Large Wooden Door",
    "Warp 5 Pad",
    "Warp 3 Pad",
    "Warp 4 Pad",
    "Warp 2 Pad",
    "Warp 1 Pad",
    "Large Door",
    "Library Door (Revolving?)",
    "Blue Platform",
    "White Platform",
    "Wooden Platform",
    "Wooden Bridge",
    "Wooden Door",
    "Metal Grate",
    "Metal Door",
    "Large Metal Door",
    "Rotating Chair",
    "Baboon Balloon Pad (with platform)",
    "Large Aztec Door",
    "Large Aztec Door",
    "Large Wooden Door",
    "Large Breakable Wooden Door",
    "Pineapple Switch (Rotating)",
    ": Pad",
    "Triangle Pad",
    "+ Pad",
    "Stone Monkey Head",
    "Stone Monkey Head",
    "Stone Monkey Head",
    "Door",
    "Broken Ship Piece",
    "Broken Ship Piece",
    "Broken Ship Piece",
    "Flotsam",
    "Metal Grate",
    "Treasure Chest",
    "Up Switch",
    "Down Switch",
    "DK Star",
    "Enguarde Door",
    "Trash Can",
    "Fluorescent Tube",
    "Wooden Door Half",
    "Stone Platform",
    "Stone Panel",
    "Stone Panel (Rotating)",
    "Wrinkly Door Wheel",
    "Wooden Door",
    "Wooden Panel",
    "Electricity Shields?",
    "Torch Light Source",
    "Boulder Pad (Red)",
    "Candelabra",
    "Banana Peel",
    "Skull+Candle",
    "Metal Box",
    "1 Switch",
    "2 Switch",
    "3 Switch",
    "4 Switch",
    "Metal Grate (Breakable?)",
    "Pound The X Platform",
    "Wooden Door",
    "Chandelier",
    "Bone Door",
    "Metal Bars",
    "4 Door (5DS)",
    "5 Door (5DS)",
    "Door (Llama Temple)",
    "Coffin Door",
    "Metal Bars",
    "Metal Grate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Boulder",
    "Boulder",
    "K. Rool Ship Jaw Bottom",
    "Blast-O-Matic Cover?",
    "Blast-O-Matic Cover",
    "Door",
    "Platform",
    "Propeller",
    "K. Rool's Ship",
    "Mad Jack Platform (White)",
    "Mad Jack Platform (White)",
    "Mad Jack Platform (Blue)",
    "Mad Jack Platform (Blue)",
    "Skull Gate (Minecart)",
    "Dogadon Arena Outer",
    "Boxing Ring Corner (Red)",
    "Boxing Ring Corner (Green)",
    "Boxing Ring Corner (Blue)",
    "Boxing Ring Corner (Yellow)",
    "Lightning Rod",
    "Green Electricity",
    "Blast-O-Matic",
    "Target",
    "Spotlight",
    "",
    "Vine",
    "Director's Chair",
    "Spotlight",
    "Spotlight",
    "Boom Microphone",
    "Auditions Sign",
    "Banana Hoard",
    "Boulder",
    "Boulder",
    "Rareware GB",
    "",
    "",
    "",
    "",
    "Platform (Crystal Caves Minigame)",
    "King Kut Out Arm (Bloopers)",
    "Rareware Coin",
    "Golden Banana",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Rock",
    "K. Rool's Ship",
    "",
    "",
    "",
    "Wooden Door",
    "",
    "",
    "",
    "Nothing?",
    "Troff'n'Scoff Portal",
    "Level Entry/Exit",
    "K. Lumsy Key Indicator?",
    "",
    "",
    "",
    "",
    "",
    "Red Bell",
    "Green Bell",
    "Race Checkpoint"
]
